config/routes.rb
Rails.application.routes.draw do
  resources :news
  root 'news#index'
  get'new/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :index)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Churchnote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>	
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_for(news) do |f| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :index %>
    <%= f.text_field :index %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<body>
  <nav>
    <ul>
      <li>
        <a href="">The Word</a>
        <ul>
          <li><a href="">message</a></li>
          <li><a href="">Testimony</a></li>
        </ul>
      </li>
      <li>
        <a href="">Event</a>
        <ul>
          <li><a href="">Trips</a></li>
          <li><a href="">Fasting</a></li>
        </ul>
      </li>
      <!-- etc. -->
    </ul>
  </nav>


  <div class="row1">

  <div class="blog">
    <div class="blog2">
    <div class="row">
      <div class="col s7 push-s5"><span class="flow-text">
      <h3>Sunday Message</h3>
        <span class="date" style="font-size:12px;"> October 30, 2016</span>

        <span style="font-size:20px; color:green;"><p></p></span>

        <h5>Don't give away what you have.</h5>.</span>

        <p>Know What God is to you.Kow What He's done for you.</p>

        <p style="font-size:20px;color:white; font-family:impact;">Now as Christian are job is to not be like the people in 2Timothy 3:7.<br>
          "Ever learning, and never coming to the full knowledge of christ."<br>
          Only Qaulified people, who come into the full knowledge of Christ,<br>
          will have a chance to make it.People in the natural government <br>
          would not able to be there if they did not experience.<br>
          Now as Christian it is time to learn all that we need to become a part of the bride of Christ. </p> 

          <span style="font-size:20px; color:green;"><p></p></span>

        <p style="font-size:20px;color:white; font-family:impact;" >The message continue:<br><br>
        God took us from four point of the earth as it mention in the book of Luke 13:29 .<br>
        He went on, to show we can find the Lord, through faith. In Matthew 8:6-7.<br> The servant went to find Jesus Christ by faith and humble before Him.<br> Brother Noel<br>
        Went on back to the same topic. of 2 Timothy 3 <br> 
        <strong style="color:blue;font-size:25px;">Things we should not</strong><br>
        "For men shall be lovers of their own selves".
        <ul style="font-size:20px;color:black; font-family:impact;">
          <li> covetous, boasters, proud, blasphemers, </li><br>
          <li> disobedient to parents, unthankful, unholy,</li><br>
                   <li> Without natural affection, trucebreakers, false accusers</li><br> 
                   <li>incontinent, fierce, despisers of those that are good,</li><br>
                   <li> Traitors, heady, highminded, lovers of pleasures more than lovers of God;</li> <br>
        </ul>
        </p>
        <p  style="font-size:22px;color:white; font-family:impact;">
         Having a form of godliness, but denying the power thereof: from such turn away.<br>
          For of this sort are they which creep into houses,<br>
        and lead captive silly women laden with sins, led away with divers lusts,<br>
        the faith  of the religion world is set on natural things; houses, money, cars.<br>
         but as Christain is set on above. that is why we should strive daily <br>
         and always ask God to help us on the way.<br>
         Ask for His strenght, strenght for your mind, spirit <br>
         and so you won't do your own will but God's.<strong>God Bless</strong> 

        </p>

        </div>

        <div class="col s5 pull-s7" style=" margin-top:3em;
        padding-top:1em; color:white;">
        <span class="flow-text">
        <h5>God Is Up Head</h5>
        <p style="font-size:20px;color:white; font-family:impact;">

        There are time you will feel<br>
         like you can't do it on your own.<br> 
         Just know you can always call on<br> 
         God for a miracle.Some time <br> 
         you will not see the end of the storm <br>
         but know there's hope in font of you,<br> 
         there's a big sun shinnig up a head,<br>
         you just have to keep striving, <br>
         and stay on your knee for your new day<br>
         is up head.you just have to believe that<br>
         God is with you and He is your only hope.
        </p>
             </span></div>

        <div class="col s5 pull-s7" style=" margin-top:3em;
        padding-top:1em;"><span class="flow-text"><h5>You Are A Blessing.</h5>.
        <p style="color:black; font-size:22px; font-family:impact;">
          Count your blessings Name them one by one <br>
          Count your blessings See what God has done<br>
          Count your blessings 'Till all this well with your soul<br>
          Count your blessings Move on the past you down<br>
          Count your blessings When fear's screaming loud<br>
          Count your blessings Until your heart overflows
        </p></span></div>

        <div class="col s5 pull-s7" style=" margin-top:3em;
        padding-top:1em;"><span class="flow-text"><h5>You Are A Miracle.</h5>
        <p style="font-size:20px;color:white; font-family:impact;">  You life is a miracle<br>
        can you believe you a miracle? <br>
        the next time you feel down know that<br>
         you are miracle and God is ready to help you.<br>
        remember the key is to never give up on God. <br>  
        <a href=""></a>Examine yoursel daily.
        </p>
        </span></div>
      </div>
    </div>

  </div>



<div class="devotion">

  <div class="row">
    <div class="col s12 m4 l2">
   
         <%= image_tag("devotion.jpg", height:'700', width: '400',)  %>
  
    <h5 style="color:green;">  Devotion</h5>
    <div class="ui three column grid">
      <div class="column">
      </div>
    </div></p>
  </div>


  <div class="col s12 m6 l3"> <h5>Suffer With God.</h5> <p style="color:white; font-size:17px;">God is an awsome God.Serving God May not always be easy, because it wasm't easy for Jesus Christ. here's what 2 Corinthians 1:7 tells us."And our hope of you is stedfast, knowing, that as ye are partakers of the sufferings, so shall ye be also of the consolation." In Philippians 3:10 "That I may know him, and the power of his resurrection, and the fellowship of his sufferings, being made conformable unto his death;".Suffering with the Lord is our job.
  </p></div>

    <div class="col s12 m6 l3">
      <p style="color:#820402;font-size:17px;">
        <h5>The elements that we need in the lord. are the fruit of the Spirit:</h5>
        <ul class="list">
            <li> Love,</li>
            <li> Joy,</li>
            <li> Peace,</li>
            <li> Longsuffering, </li>
            <li> gentleness, </li>
            <li> goodness, </li>
            <li> Faith, </li>
             Meekness,and temperance. because if we live in the spirit we will walk in the spirit.
        </ul>
       
      </p>

    </div>

     

      <div class="col s24 m12 l3">
      <h5>God Is Not Man, That Should lie.</h5> 
      Numbers23:19  
      <p style="color:white; font-size:17px" > 
      God is faithful to us all,He never failed us.Even though many time we let Him down but with is prefect Love He always there for us. Romans8:28 Shows His faithfulness to us ."We know that for those who love God all things work together for good, for those who are called according to his purpose." 
      </p>
      </div>

      <div class="col s12 m6 l3"> <h5>Love One Another.</h5> <p style="color:white; font-size:17px"> Jesus Christ the true defintion of love. Jesus did not only die for us but, He lived an example for us. He show us how to love. John 13:34-35"A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.By this shall all men know that ye are my disciples, if ye have love one to another. "</p></div>

</div>





<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Index:</strong>
  <%= @news.index %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>